import type { Topic } from "../types";
import { unpack } from "./codec";
import { bankFill, bankMCQ, pick, shuffle } from "./utils";

const cap = (s: string) => `${s[0].toUpperCase()}${s.slice(1)}`;
const article = (word: string) => (/^[aeiou]/i.test(word) ? "an" : "a");

const COMPOUND: [string, string, string][] = unpack("W1sic3VuIiwiZmxvd2VyIiwic3VuZmxvd2VyIl0sWyJyYWluIiwiYm93IiwicmFpbmJvdyJdLFsiZm9vdCIsImJhbGwiLCJmb290YmFsbCJdLFsiYnV0dGVyIiwiZmx5IiwiYnV0dGVyZmx5Il0sWyJjdXAiLCJjYWtlIiwiY3VwY2FrZSJdLFsidG9vdGgiLCJicnVzaCIsInRvb3RoYnJ1c2giXSxbInN0YXIiLCJmaXNoIiwic3RhcmZpc2giXSxbInNub3ciLCJtYW4iLCJzbm93bWFuIl0sWyJzYWlsIiwiYm9hdCIsInNhaWxib2F0Il0sWyJib29rIiwic2hlbGYiLCJib29rc2hlbGYiXSxbImJlZCIsInJvb20iLCJiZWRyb29tIl0sWyJhaXIiLCJwbGFuZSIsImFpcnBsYW5lIl0sWyJtb29uIiwibGlnaHQiLCJtb29ubGlnaHQiXSxbInBhbiIsImNha2UiLCJwYW5jYWtlIl0sWyJoYW5kIiwiYmFnIiwiaGFuZGJhZyJdLFsid2F0ZXIiLCJmYWxsIiwid2F0ZXJmYWxsIl0sWyJkb29yIiwiYmVsbCIsImRvb3JiZWxsIl0sWyJzZWEiLCJzaGVsbCIsInNlYXNoZWxsIl0sWyJiYWNrIiwicGFjayIsImJhY2twYWNrIl0sWyJuZXdzIiwicGFwZXIiLCJuZXdzcGFwZXIiXV0=");
const SENTENCE_TYPES: [string, string][] = unpack("W1siVGhlIHN1biBpcyBzaGluaW5nIHRvZGF5LiIsInN0YXRlbWVudCJdLFsiV2hlcmUgZGlkIHlvdSBwdXQgbXkgaGF0PyIsInF1ZXN0aW9uIl0sWyJXaGF0IGEgYmVhdXRpZnVsIGRheSBpdCBpcyEiLCJleGNsYW1hdGlvbiJdLFsiQ2xvc2UgdGhlIGRvb3IsIHBsZWFzZS4iLCJjb21tYW5kIl0sWyJNeSBjYXQgbGlrZXMgdG8gc2xlZXAgb24gdGhlIHNvZmEuIiwic3RhdGVtZW50Il0sWyJDYW4gd2UgZ28gdG8gdGhlIHBhcms/IiwicXVlc3Rpb24iXSxbIldvdywgdGhhdCB3YXMgYW1hemluZyEiLCJleGNsYW1hdGlvbiJdLFsiUGxlYXNlIHNpdCBkb3duLiIsImNvbW1hbmQiXSxbIldlIGFyZSBoYXZpbmcgcGFzdGEgZm9yIGRpbm5lci4iLCJzdGF0ZW1lbnQiXSxbIldobyBpcyB5b3VyIGJlc3QgZnJpZW5kPyIsInF1ZXN0aW9uIl0sWyJJIGNhbid0IGJlbGlldmUgd2Ugd29uISIsImV4Y2xhbWF0aW9uIl0sWyJQdXQgeW91ciBzaG9lcyBvbi4iLCJjb21tYW5kIl0sWyJUaGUgYnVzIGxlYXZlcyBhdCBlaWdodCBvJ2Nsb2NrLiIsInN0YXRlbWVudCJdLFsiSG93IG9sZCBhcmUgeW91PyIsInF1ZXN0aW9uIl0sWyJXYXRjaCBvdXQgZm9yIHRoYXQgcHVkZGxlISIsImV4Y2xhbWF0aW9uIl0sWyJXYXNoIHlvdXIgaGFuZHMgYmVmb3JlIGx1bmNoLiIsImNvbW1hbmQiXSxbIkJpcmRzIGJ1aWxkIG5lc3RzIGluIHRyZWVzLiIsInN0YXRlbWVudCJdLFsiSXMgaXQgdGltZSB0byBnbyBob21lIHlldD8iLCJxdWVzdGlvbiJdLFsiTG9vayBhdCB0aGUgcmFpbmJvdyEiLCJleGNsYW1hdGlvbiJdLFsiQnJpbmcgeW91ciBib29rIHRvIHNjaG9vbCB0b21vcnJvdy4iLCJjb21tYW5kIl1d");
const SPELL_EASY: [string, string[], string][] = unpack("W1siYmVjYXVzZSIsWyJiZWN1eiIsImJlY2FzZSIsImJlY2F1cyJdLCIiXSxbImZyaWVuZCIsWyJmcmVpbmQiLCJmcmVuZCIsImZpcmVuZCJdLCJJdCBoYXMgJ2VuZCcgYXQgdGhlIGZpbmlzaDogZnJpLUVORC4iXSxbInNjaG9vbCIsWyJzY29vbCIsInNoY29vbCIsInNrb29sIl0sIiJdLFsicGVvcGxlIixbInBlcGxlIiwicGVlcGxlIiwicG9lcGxlIl0sIiJdLFsibW90aGVyIixbIm1vdGhhciIsIm11dGhlciIsIm1vdGhvciJdLCIiXSxbIndhdGVyIixbIndhdHRlciIsIndvdGFyIiwid2FydGVyIl0sIiJdLFsiYWdhaW4iLFsiYWdlbiIsImFnaWFuIiwiYWdpbiJdLCIiXSxbImxpdHRsZSIsWyJsaXRsZSIsImxpdHRlbCIsImxpdHRhbCJdLCIiXSxbImFsd2F5cyIsWyJhbGx3YXlzIiwib2x3YXlzIiwiYWx3YXllcyJdLCJJdCBpcyAnYWxsJyArICd3YXlzJyB3aXRoIG9ubHkgb25lIGw6IGFsLXdheXMuIl0sWyJicm90aGVyIixbImJydXRoZXIiLCJicm90aGFyIiwiYnJvdGhvciJdLCIiXSxbImhvdXNlIixbImhvdXMiLCJob3dzZSIsImhvd3MiXSwiSXQgZW5kcyB3aXRoIGEgc2lsZW50IGUuIl0sWyJzaXN0ZXIiLFsic2lzdGFyIiwic2lzc3RlciIsInNpc3R1ciJdLCIiXSxbInRvZGF5IixbInRvZGFpIiwidHVkYXkiLCJ0by1kYXkiXSwiIl0sWyJjaG9jb2xhdGUiLFsiY2hvY2xhdGUiLCJjaG9jb2xhdCIsImNob2NhbGF0ZSJdLCIiXSxbInRvZ2V0aGVyIixbInRvZ2V0aGFyIiwidG9nZWF0aGVyIiwidG9naGV0aGVyIl0sIkl0IGlzIG1hZGUgb2YgJ3RvJyArICdnZXQnICsgJ2hlcicuIl0sWyJhbmltYWwiLFsiYW5pbWVsIiwiYW5hbWFsIiwiYW5pbXVsbCJdLCIiXV0=");
const SPELL_HARD: [string, string[], string][] = unpack("W1sibmVjZXNzYXJ5IixbIm5lY2Nlc3NhcnkiLCJuZWNlc2FyeSIsIm5lY2Nlc2FyeSJdLCJSZW1lbWJlcjogb25lIGNvbGxhciAoYykgYW5kIHR3byBzbGVldmVzIChzKS4iXSxbInNlcGFyYXRlIixbInNlcGVyYXRlIiwic2VwYXJldGUiLCJzZXBlcmV0ZSJdLCJUaGVyZSBpcyAnYSByYXQnIGluIHNlcC1hLXJhdGUuIl0sWyJkZWZpbml0ZWx5IixbImRlZmluYXRlbHkiLCJkZWZpbml0bHkiLCJkZWZlbml0ZWx5Il0sIkl0IGhhcyB0aGUgd29yZCAnZmluaXRlJyBpbnNpZGUgaXQuIl0sWyJsaWJyYXJ5IixbImxpYmFyeSIsImxpYmVycnkiLCJsaWJhcnJ5Il0sIlNheSBpdCBzbG93bHk6IGxpLWJyYXIteS4iXSxbIkZlYnJ1YXJ5IixbIkZlYnVhcnkiLCJGZWJ1cmFyeSIsIkZlYnJhcnkiXSwiU2F5IHRoZSByOiBGZWItcnUtYXJ5LiJdLFsiYmVhdXRpZnVsIixbImJldXRpZnVsIiwiYmVhdXRpZnVsbCIsImJ1dGlmdWwiXSwiU3VmZml4IC1mdWwgaGFzIG9ubHkgb25lIGwuIl0sWyJkaWZmZXJlbnQiLFsiZGlmZnJlbnQiLCJkaWZlcmVudCIsImRpZmZlcmFudCJdLCJJdCBoYXMgdHdvIGYncyBhbmQgZW5kcyBpbiAtZW50LiJdLFsiaW50ZXJlc3RpbmciLFsiaW50cmVzdGluZyIsImludGVycmVzdGluZyIsImludGVyc3RpbmciXSwiIl0sWyJXZWRuZXNkYXkiLFsiV2Vuc2RheSIsIldlZG5zZGF5IiwiV2VuZGVzZGF5Il0sIlNheSBpdCBhcyBXZWRuZXMtZGF5LCB3aXRoIHRoZSBkIGJlZm9yZSBuZXMuIl0sWyJ0b21vcnJvdyIsWyJ0b21tb3JvdyIsInRvbW9yb3ciLCJ0b21tb3Jyb3ciXSwiT25lIG0gYW5kIHR3byByJ3M6IHRvLW1vLXJyb3cuIl0sWyJyZWNlaXZlIixbInJlY2lldmUiLCJyZWNldmUiLCJyZWNpdmUiXSwiSSBiZWZvcmUgZSwgZXhjZXB0IGFmdGVyIGMuIl0sWyJiZWxpZXZlIixbImJlbGVpdmUiLCJiZWxpdmUiLCJiZWxldmUiXSwiSSBiZWZvcmUgZTogdGhlcmUgaXMgYSAnbGllJyBpbiBiZS1saWUtdmUuIl0sWyJkaXNhcHBlYXIiLFsiZGlzc2FwZWFyIiwiZGlzYXBlYXIiLCJkaXNzYXBwZWFyIl0sIkl0IGlzIGRpcy0gKyBhcHBlYXI6IG9uZSBzIGFuZCBvbmUgcC4iXSxbImVtYmFycmFzcyIsWyJlbWJhcmFzcyIsImVtYmFycmFzIiwiZW1iYXJyZXNzIl0sIkl0IGhhcyB0d28gcidzIGFuZCB0d28gcydzLiJdLFsiZ292ZXJubWVudCIsWyJnb3Zlcm1lbnQiLCJnb3Zlbm1lbnQiLCJnb3Zlcm5tYW50Il0sIlNheSB0aGUgbjogZ292ZXItbi1tZW50LiJdLFsiaW1tZWRpYXRlbHkiLFsiaW1tZWRpYXRseSIsImltZWRpYXRlbHkiLCJpbW1lZGlhdGxleSJdLCIiXSxbIm9jY2FzaW9uIixbIm9jYXNpb24iLCJvY2Nhc3Npb24iLCJvY2Fzc2lvbiJdLCJUd28gYydzIGFuZCBvbmUgcy4iXSxbInN1cnByaXNlIixbInN1cHJpc2UiLCJzdXJwcml6ZSIsInN1cnByaWNlIl0sIlNheSB0aGUgZmlyc3Qgcjogc3VyLXByaXNlLiJdLFsiY2FsZW5kYXIiLFsiY2FsZW5kZXIiLCJjYWxhbmRhciIsImNhbGFuZGVyIl0sIkl0IGVuZHMgaW4gLWFyLiJdLFsid2VpZ2h0IixbIndpZWdodCIsIndlaWd0aCIsIndoZWlnaHQiXSwiSXQgaGFzICdlaWdoJyBpbiB0aGUgbWlkZGxlLCBsaWtlICdlaWdodCcuIl1d");
const SUFFIXES: [string, string, string, string][] = unpack("W1siY2FyZSIsImZ1bCIsImNhcmVmdWwiLCItZnVsIG1lYW5zICdmdWxsIG9mJy4iXSxbImhlbHAiLCJsZXNzIiwiaGVscGxlc3MiLCItbGVzcyBtZWFucyAnd2l0aG91dCcuIl0sWyJraW5kIiwibmVzcyIsImtpbmRuZXNzIiwiLW5lc3MgdHVybnMgYW4gYWRqZWN0aXZlIGludG8gYSBub3VuLiJdLFsicXVpY2siLCJseSIsInF1aWNrbHkiLCItbHkgdHVybnMgYW4gYWRqZWN0aXZlIGludG8gYW4gYWR2ZXJiLiJdLFsiaGFwcHkiLCJuZXNzIiwiaGFwcGluZXNzIiwiLW5lc3MgdHVybnMgYW4gYWRqZWN0aXZlIGludG8gYSBub3VuLiBUaGUgeSBjaGFuZ2VzIHRvIGkgYmVmb3JlIHRoZSBzdWZmaXguIl0sWyJob3BlIiwiZnVsIiwiaG9wZWZ1bCIsIi1mdWwgbWVhbnMgJ2Z1bGwgb2YnLiJdLFsidGVhY2giLCJlciIsInRlYWNoZXIiLCItZXIgbWVhbnMgJ2EgcGVyc29uIHdobyBkb2VzIHNvbWV0aGluZycuIl0sWyJwbGF5IiwiZnVsIiwicGxheWZ1bCIsIi1mdWwgbWVhbnMgJ2Z1bGwgb2YnLiJdLFsiY2hpbGQiLCJpc2giLCJjaGlsZGlzaCIsIi1pc2ggbWVhbnMgJ2xpa2UnIG9yICdzb21ld2hhdCcuIl0sWyJzYWQiLCJseSIsInNhZGx5IiwiLWx5IHR1cm5zIGFuIGFkamVjdGl2ZSBpbnRvIGFuIGFkdmVyYi4iXSxbImhhcHB5IiwibHkiLCJoYXBwaWx5IiwiLWx5IHR1cm5zIGFuIGFkamVjdGl2ZSBpbnRvIGFuIGFkdmVyYi4gVGhlIHkgY2hhbmdlcyB0byBpIGJlZm9yZSB0aGUgc3VmZml4LiJdLFsiYmVhdXR5IiwiZnVsIiwiYmVhdXRpZnVsIiwiLWZ1bCBtZWFucyAnZnVsbCBvZicuIFRoZSB5IGNoYW5nZXMgdG8gaSBiZWZvcmUgdGhlIHN1ZmZpeC4iXSxbImZlYXIiLCJsZXNzIiwiZmVhcmxlc3MiLCItbGVzcyBtZWFucyAnd2l0aG91dCcuIl0sWyJqb3kiLCJmdWwiLCJqb3lmdWwiLCItZnVsIG1lYW5zICdmdWxsIG9mJy4iXSxbImNoZWVyIiwiZnVsIiwiY2hlZXJmdWwiLCItZnVsIG1lYW5zICdmdWxsIG9mJy4iXSxbInBhaW50IiwiZXIiLCJwYWludGVyIiwiLWVyIG1lYW5zICdhIHBlcnNvbiB3aG8gZG9lcyBzb21ldGhpbmcnLiJdLFsidGhvdWdodCIsImxlc3MiLCJ0aG91Z2h0bGVzcyIsIi1sZXNzIG1lYW5zICd3aXRob3V0Jy4iXSxbInNsZWVwIiwibGVzcyIsInNsZWVwbGVzcyIsIi1sZXNzIG1lYW5zICd3aXRob3V0Jy4iXSxbImZyaWVuZCIsInNoaXAiLCJmcmllbmRzaGlwIiwiLXNoaXAgbmFtZXMgYSBzdGF0ZSBvciByZWxhdGlvbnNoaXAuIl0sWyJkYW5nZXIiLCJvdXMiLCJkYW5nZXJvdXMiLCItb3VzIG1lYW5zICdmdWxsIG9mJy4iXV0=");
const AGREEMENT: [string, string, string, string][] = unpack("W1siVGhlIGRvZyBfX18gbG91ZGx5IGF0IHRoZSBwb3N0bWFuLiIsImJhcmtzIiwiYmFyayIsIlRoZSBzdWJqZWN0ICdkb2cnIGlzIHNpbmd1bGFyLCBzbyB0aGUgdmVyYiB0YWtlcyAtcy4iXSxbIk15IGZyaWVuZHMgX19fIGNvbWluZyB0byB0aGUgcGFydHkuIiwiYXJlIiwiaXMiLCInRnJpZW5kcycgaXMgcGx1cmFsLCBzbyB1c2UgJ2FyZScuIl0sWyJTaGUgX19fIGEgcmVkIGJpa2UuIiwiaGFzIiwiaGF2ZSIsIldpdGggaGUsIHNoZSBhbmQgaXQsIHVzZSAnaGFzJy4iXSxbIlRoZXkgX19fIGxhdGUgZm9yIHNjaG9vbC4iLCJ3ZXJlIiwid2FzIiwiJ1RoZXknIGlzIHBsdXJhbCwgc28gdXNlICd3ZXJlJy4iXSxbIlRoZSBib3kgYW5kIHRoZSBnaXJsIF9fXyBwbGF5aW5nIG91dHNpZGUuIiwiYXJlIiwiaXMiLCJUd28gcGVvcGxlIGpvaW5lZCBieSAnYW5kJyBtYWtlIGEgcGx1cmFsIHN1YmplY3QsIHNvIHVzZSAnYXJlJy4iXSxbIkhlIF9fXyBsaWtlIHBlYXMuIiwiZG9lc24ndCIsImRvbid0IiwiV2l0aCBoZSwgc2hlIGFuZCBpdCwgdXNlICdkb2Vzbid0Jy4iXSxbIlRoZSBjaGlsZHJlbiBfX18gaW4gdGhlIGdhcmRlbi4iLCJwbGF5IiwicGxheXMiLCInQ2hpbGRyZW4nIGlzIHBsdXJhbCwgc28gdGhlIHZlcmIgaGFzIG5vIC1zLiJdLFsiVGhlIGJvb2tzIG9uIHRoZSBzaGVsZiBfX18gb2xkLiIsImFyZSIsImlzIiwiVGhlIHN1YmplY3QgaXMgJ2Jvb2tzJyAocGx1cmFsKSwgbm90ICdzaGVsZicuIl0sWyJFYWNoIG9mIHRoZSBzdHVkZW50cyBfX18gYSBwZW5jaWwuIiwiaGFzIiwiaGF2ZSIsIidFYWNoJyBpcyBzaW5ndWxhciwgc28gdXNlICdoYXMnLiJdLFsiTXkgc2lzdGVyIGFuZCBJIF9fXyBnb2luZyB0byB0aGUgYmVhY2guIiwiYXJlIiwiYW0iLCInTXkgc2lzdGVyIGFuZCBJJyBpcyBwbHVyYWwsIHNvIHVzZSAnYXJlJy4iXSxbIkEgZmxvY2sgb2YgYmlyZHMgX19fIGZseWluZyBvdmVyaGVhZC4iLCJ3YXMiLCJ3ZXJlIiwiVGhlIHN1YmplY3QgaXMgJ2Zsb2NrJyAob25lIGdyb3VwKSwgc28gdXNlIHRoZSBzaW5ndWxhciAnd2FzJy4iXSxbIlRoZSBjYXRzIF9fXyBhc2xlZXAgb24gdGhlIHNvZmEuIiwiYXJlIiwiaXMiLCInQ2F0cycgaXMgcGx1cmFsLCBzbyB1c2UgJ2FyZScuIl0sWyJFdmVyeW9uZSBfX18gcmVhZHkgdG8gc3RhcnQuIiwiaXMiLCJhcmUiLCInRXZlcnlvbmUnIGlzIHNpbmd1bGFyLCBzbyB1c2UgJ2lzJy4iXSxbIldlIF9fXyBvdXIgaG9tZXdvcmsgeWVzdGVyZGF5LiIsImRpZCIsImRvbmUiLCJVc2UgJ2RpZCcgZm9yIHRoZSBzaW1wbGUgcGFzdDsgJ2RvbmUnIG5lZWRzIGEgaGVscGVyIHN1Y2ggYXMgJ2hhdmUnLiJdLFsiVGhlIHRlYWNoZXIgX19fIHRoZSBjbGFzcyBldmVyeSBtb3JuaW5nLiIsImdyZWV0cyIsImdyZWV0IiwiVGhlIHN1YmplY3QgJ3RlYWNoZXInIGlzIHNpbmd1bGFyLCBzbyB0aGUgdmVyYiB0YWtlcyAtcy4iXSxbIk5laXRoZXIgb2YgdGhlIGJveXMgX19fIGZpbmlzaGVkLiIsImhhcyIsImhhdmUiLCInTmVpdGhlcicgaXMgc2luZ3VsYXIsIHNvIHVzZSAnaGFzJy4iXSxbIlRoZSBwbGF5ZXJzIF9fXyBwcmFjdGlzaW5nIGhhcmQuIiwiYXJlIiwiaXMiLCInUGxheWVycycgaXMgcGx1cmFsLCBzbyB1c2UgJ2FyZScuIl0sWyJNdW0gYW5kIERhZCBfX18gaG9tZSBub3cuIiwiYXJlIiwiaXMiLCJUd28gcGVvcGxlIGpvaW5lZCBieSAnYW5kJyBtYWtlIGEgcGx1cmFsIHN1YmplY3QsIHNvIHVzZSAnYXJlJy4iXV0=");
const POSSESSIVE: [string, string, string[], string][] = unpack("W1sidGhlIGJvbmUgYmVsb25ncyB0byBvbmUgZG9nIiwidGhlIGRvZydzIGJvbmUiLFsidGhlIGRvZ3MgYm9uZSIsInRoZSBkb2dzJyBib25lIiwidGhlIGRvZyBib25lJ3MiXSwiT25lIG93bmVyOiBhZGQgJ3MgdG8gdGhlIHNpbmd1bGFyIG5vdW4uIl0sWyJ0aGUgY29hdHMgYmVsb25nIHRvIHNldmVyYWwgZ2lybHMiLCJ0aGUgZ2lybHMnIGNvYXRzIixbInRoZSBnaXJsJ3MgY29hdHMiLCJ0aGUgZ2lybHMgY29hdHMiLCJ0aGUgZ2lybHMncyBjb2F0cyJdLCJTZXZlcmFsIG93bmVyczogdGhlIHBsdXJhbCBhbHJlYWR5IGVuZHMgaW4gcywgc28gYWRkIGp1c3QgYW4gYXBvc3Ryb3BoZSBhZnRlciBpdC4iXSxbInRoZSB0b3lzIGJlbG9uZyB0byB0aGUgY2hpbGRyZW4iLCJ0aGUgY2hpbGRyZW4ncyB0b3lzIixbInRoZSBjaGlsZHJlbnMnIHRveXMiLCJ0aGUgY2hpbGRyZW5zIHRveXMiLCJ0aGUgY2hpbGRyZW4gdG95cyciXSwiJ0NoaWxkcmVuJyBpcyBhIHBsdXJhbCB0aGF0IGRvZXMgbm90IGVuZCBpbiBzLCBzbyBhZGQgJ3MuIl0sWyJ0aGUgY2FyIGJlbG9uZ3MgdG8gbXkgbW90aGVyIiwibXkgbW90aGVyJ3MgY2FyIixbIm15IG1vdGhlcnMgY2FyIiwibXkgbW90aGVycycgY2FyIiwibXkgbW90aGVyIGNhcidzIl0sIk9uZSBvd25lcjogYWRkICdzIHRvIHRoZSBzaW5ndWxhciBub3VuLiJdLFsidGhlIHJvb20gaXMgdXNlZCBieSBhbGwgdGhlIHRlYWNoZXJzIiwidGhlIHRlYWNoZXJzJyByb29tIixbInRoZSB0ZWFjaGVyJ3Mgcm9vbSIsInRoZSB0ZWFjaGVycyByb29tIiwidGhlIHRlYWNoZXJzJ3Mgcm9vbSJdLCJTZXZlcmFsIG93bmVyczogYWRkIGp1c3QgYW4gYXBvc3Ryb3BoZSBhZnRlciB0aGUgcGx1cmFsIHMuIl0sWyJ0aGUgdGFpbCBiZWxvbmdzIHRvIHRoZSBjYXQiLCJ0aGUgY2F0J3MgdGFpbCIsWyJ0aGUgY2F0cyB0YWlsIiwidGhlIGNhdHMnIHRhaWwiLCJ0aGUgY2F0IHRhaWwncyJdLCJPbmUgb3duZXI6IGFkZCAncy4iXSxbInRoZSBib29rcyBiZWxvbmcgdG8gdHdvIGJveXMiLCJ0aGUgYm95cycgYm9va3MiLFsidGhlIGJveSdzIGJvb2tzIiwidGhlIGJveXMgYm9va3MiLCJ0aGUgYm95cydzIGJvb2tzIl0sIlNldmVyYWwgb3duZXJzOiBhZGQganVzdCBhbiBhcG9zdHJvcGhlIGFmdGVyIHRoZSBwbHVyYWwgcy4iXSxbInRoZSBuZXN0IGJlbG9uZ3MgdG8gYSBiaXJkIiwidGhlIGJpcmQncyBuZXN0IixbInRoZSBiaXJkcyBuZXN0IiwidGhlIGJpcmRzJyBuZXN0IiwidGhlIGJpcmQgbmVzdCdzIl0sIk9uZSBvd25lcjogYWRkICdzLiJdLFsidGhlIHdvb2wgYmVsb25ncyB0byB0aGUgc2hlZXAiLCJ0aGUgc2hlZXAncyB3b29sIixbInRoZSBzaGVlcHMgd29vbCIsInRoZSBzaGVlcHMnIHdvb2wiLCJ0aGUgc2hlZXAgd29vbCdzIl0sIidTaGVlcCcgaXMgdGhlIHNhbWUgc2luZ3VsYXIgYW5kIHBsdXJhbCBhbmQgZG9lcyBub3QgZW5kIGluIHMsIHNvIGFkZCAncy4iXSxbInRoZSBjaGFuZ2luZyByb29tIGlzIGZvciB0aGUgd29tZW4iLCJ0aGUgd29tZW4ncyBjaGFuZ2luZyByb29tIixbInRoZSB3b21lbnMnIGNoYW5naW5nIHJvb20iLCJ0aGUgd29tZW5zIGNoYW5naW5nIHJvb20iLCJ0aGUgd29tYW4ncyBjaGFuZ2luZyByb29tIl0sIidXb21lbicgaXMgYSBwbHVyYWwgdGhhdCBkb2VzIG5vdCBlbmQgaW4gcywgc28gYWRkICdzLiJdLFsidGhlIGx1bmNoIGJlbG9uZ3MgdG8gb25lIHN0dWRlbnQiLCJ0aGUgc3R1ZGVudCdzIGx1bmNoIixbInRoZSBzdHVkZW50cyBsdW5jaCIsInRoZSBzdHVkZW50cycgbHVuY2giLCJ0aGUgc3R1ZGVudCBsdW5jaCdzIl0sIk9uZSBvd25lcjogYWRkICdzLiJdLFsidGhlIHJ1bGVzIGFyZSBtYWRlIGJ5IHRoZSBzY2hvb2wiLCJ0aGUgc2Nob29sJ3MgcnVsZXMiLFsidGhlIHNjaG9vbHMgcnVsZXMiLCJ0aGUgc2Nob29scycgcnVsZXMiLCJ0aGUgc2Nob29sIHJ1bGVzJ3MiXSwiT25lIG93bmVyOiBhZGQgJ3MuIl0sWyJ0aGUgcGxheWdyb3VuZCBpcyB1c2VkIGJ5IG1hbnkgcHVwaWxzIiwidGhlIHB1cGlscycgcGxheWdyb3VuZCIsWyJ0aGUgcHVwaWwncyBwbGF5Z3JvdW5kIiwidGhlIHB1cGlscyBwbGF5Z3JvdW5kIiwidGhlIHB1cGlscydzIHBsYXlncm91bmQiXSwiU2V2ZXJhbCBvd25lcnM6IGFkZCBqdXN0IGFuIGFwb3N0cm9waGUgYWZ0ZXIgdGhlIHBsdXJhbCBzLiJdLFsidGhlIHdpbmdzIGJlbG9uZyB0byB0aGUgYnV0dGVyZmxpZXMiLCJ0aGUgYnV0dGVyZmxpZXMnIHdpbmdzIixbInRoZSBidXR0ZXJmbHkncyB3aW5ncyIsInRoZSBidXR0ZXJmbGllcyB3aW5ncyIsInRoZSBidXR0ZXJmbGllcydzIHdpbmdzIl0sIlNldmVyYWwgb3duZXJzOiB0aGUgcGx1cmFsIGFscmVhZHkgZW5kcyBpbiBzLCBzbyBhZGQganVzdCBhbiBhcG9zdHJvcGhlLiJdXQ==");
const STRUCTURE: [string, string][] = unpack("W1siVGhlIGNhdCBzYXQgb24gdGhlIG1hdC4iLCJzaW1wbGUiXSxbIkkgd2FudGVkIHRvIGdvIG91dCwgYnV0IGl0IHdhcyByYWluaW5nLiIsImNvbXBvdW5kIl0sWyJBbHRob3VnaCBpdCB3YXMgcmFpbmluZywgd2Ugd2VudCBmb3IgYSB3YWxrLiIsImNvbXBsZXgiXSxbIlNhbSBwbGF5cyBmb290YmFsbCBhbmQgY3JpY2tldC4iLCJzaW1wbGUiXSxbIlNoZSBzdHVkaWVkIGhhcmQsIHNvIHNoZSBwYXNzZWQgdGhlIHRlc3QuIiwiY29tcG91bmQiXSxbIldoZW4gdGhlIGJlbGwgcmFuZywgdGhlIHN0dWRlbnRzIGxlZnQgdGhlIHJvb20uIiwiY29tcGxleCJdLFsiVGhlIGNoaWxkcmVuIGxhdWdoZWQuIiwic2ltcGxlIl0sWyJJIGxpa2UgdGVhLCBhbmQgbXkgc2lzdGVyIGxpa2VzIGNvZmZlZS4iLCJjb21wb3VuZCJdLFsiQmVjYXVzZSBoZSB3YXMgdGlyZWQsIGhlIHdlbnQgdG8gYmVkIGVhcmx5LiIsImNvbXBsZXgiXSxbIlRoZSBvbGQgbWFuIHdhbGtlZCBzbG93bHkgYWxvbmcgdGhlIGJlYWNoLiIsInNpbXBsZSJdLFsiV2UgY291bGQgd2FsayB0byB0aGUgc2hvcCwgb3Igd2UgY291bGQgY2F0Y2ggdGhlIGJ1cy4iLCJjb21wb3VuZCJdLFsiVGhlIHRlYW0gY2VsZWJyYXRlZCBhZnRlciB0aGV5IHdvbiB0aGUgZmluYWwuIiwiY29tcGxleCJdLFsiSmFtYWwgYW5kIFByaXlhIGZpbmlzaGVkIHRoZSBwcm9qZWN0LiIsInNpbXBsZSJdLFsiSXQgd2FzIGxhdGUsIHlldCBub2JvZHkgd2FudGVkIHRvIGxlYXZlLiIsImNvbXBvdW5kIl0sWyJJZiB5b3UgZmluaXNoIHlvdXIgaG9tZXdvcmssIHlvdSBjYW4gd2F0Y2ggdGVsZXZpc2lvbi4iLCJjb21wbGV4Il0sWyJUaGUgc3Rvcm0gZGFtYWdlZCBzZXZlcmFsIGhvdXNlcy4iLCJzaW1wbGUiXSxbIlRoZSB0ZWFjaGVyIHNtaWxlZCBiZWNhdXNlIHRoZSBjbGFzcyBoYWQgaW1wcm92ZWQuIiwiY29tcGxleCJdLFsiSSBjYWxsZWQgaGltLCBidXQgaGUgZGlkIG5vdCBhbnN3ZXIuIiwiY29tcG91bmQiXV0=");
const CONFUSED: [string, string, string[], string][] = unpack("W1siVGhlIHdlYXRoZXIgd2lsbCBfX18gb3VyIHBsYW5zLiIsImFmZmVjdCIsWyJlZmZlY3QiXSwiJ0FmZmVjdCcgaXMgdXN1YWxseSBhIHZlcmIgbWVhbmluZyAndG8gaW5mbHVlbmNlJzsgJ2VmZmVjdCcgaXMgdXN1YWxseSBhIG5vdW4gbWVhbmluZyAnYSByZXN1bHQnLiBIZXJlIHdlIG5lZWQgYSB2ZXJiLiJdLFsiVGhlIG1lZGljaW5lIGhhZCBhIHN0cm9uZyBfX18gb24gaGVyLiIsImVmZmVjdCIsWyJhZmZlY3QiXSwiJ0VmZmVjdCcgaXMgdXN1YWxseSBhIG5vdW4gbWVhbmluZyAnYSByZXN1bHQnOyAnYWZmZWN0JyBpcyB0aGUgdmVyYi4gSGVyZSB3ZSBuZWVkIGEgbm91bi4iXSxbIktpbSBpcyB0YWxsZXIgX19fIGhlciBicm90aGVyLiIsInRoYW4iLFsidGhlbiJdLCInVGhhbicgaXMgdXNlZCB0byBjb21wYXJlOyAndGhlbicgaXMgYWJvdXQgdGltZS4iXSxbIkZpcnN0IHdlIGF0ZSBkaW5uZXIsIF9fXyB3ZSB3ZW50IGhvbWUuIiwidGhlbiIsWyJ0aGFuIl0sIidUaGVuJyBpcyBhYm91dCB0aW1lIG9yIG9yZGVyOyAndGhhbicgaXMgdXNlZCB0byBjb21wYXJlLiJdLFsiRXZlcnlvbmUgX19fIFNhbSBjYW1lIHRvIHRoZSBwYXJ0eS4iLCJleGNlcHQiLFsiYWNjZXB0Il0sIidFeGNlcHQnIG1lYW5zICdhcGFydCBmcm9tJzsgJ2FjY2VwdCcgbWVhbnMgJ3RvIHJlY2VpdmUgb3IgYWdyZWUgdG8nLiJdLFsiUGxlYXNlIF9fXyBteSBhcG9sb2d5LiIsImFjY2VwdCIsWyJleGNlcHQiXSwiJ0FjY2VwdCcgbWVhbnMgJ3RvIHJlY2VpdmUgb3IgYWdyZWUgdG8nOyAnZXhjZXB0JyBtZWFucyAnYXBhcnQgZnJvbScuIl0sWyJUaGUgc2Nob29sIF9fXyB3ZWxjb21lZCB0aGUgbmV3IHN0dWRlbnRzLiIsInByaW5jaXBhbCIsWyJwcmluY2lwbGUiXSwiJ1ByaW5jaXBhbCcgaXMgdGhlIGhlYWQgb2YgYSBzY2hvb2wgKGFuZCBhbHNvIG1lYW5zICdtYWluJyk7ICdwcmluY2lwbGUnIGlzIGEgcnVsZSBvciBiZWxpZWYuIl0sWyJIb25lc3R5IGlzIGFuIGltcG9ydGFudCBfX18uIiwicHJpbmNpcGxlIixbInByaW5jaXBhbCJdLCInUHJpbmNpcGxlJyBpcyBhIHJ1bGUgb3IgYmVsaWVmOyAncHJpbmNpcGFsJyBpcyB0aGUgaGVhZCBvZiBhIHNjaG9vbCBvciBtZWFucyAnbWFpbicuIl0sWyJCZSBjYXJlZnVsIG5vdCB0byBfX18geW91ciBrZXlzLiIsImxvc2UiLFsibG9vc2UiXSwiJ0xvc2UnIChvbmUgbykgaXMgdGhlIHZlcmIgbWVhbmluZyAndG8gbWlzcGxhY2UnOyAnbG9vc2UnIG1lYW5zICdub3QgdGlnaHQnLiJdLFsiVGhlc2Ugc2hvZXMgYXJlIHRvbyBfX18gZm9yIG1lLiIsImxvb3NlIixbImxvc2UiXSwiJ0xvb3NlJyAodHdvIG8ncykgbWVhbnMgJ25vdCB0aWdodCc7ICdsb3NlJyBpcyB0aGUgdmVyYiAndG8gbWlzcGxhY2UnLiJdLFsiU2hlIGdhdmUgaGltIGEgX19fIG9uIGhpcyBzaW5naW5nLiIsImNvbXBsaW1lbnQiLFsiY29tcGxlbWVudCJdLCInQ29tcGxpbWVudCcgKHdpdGggYW4gaSkgaXMgcHJhaXNlOyAnY29tcGxlbWVudCcgKHdpdGggYW4gZSkgbWVhbnMgJ3NvbWV0aGluZyB0aGF0IGdvZXMgd2VsbCB3aXRoJy4iXSxbIlRoZSBzY2FyZiBpcyBhIHBlcmZlY3QgX19fIHRvIHlvdXIgY29hdC4iLCJjb21wbGVtZW50IixbImNvbXBsaW1lbnQiXSwiJ0NvbXBsZW1lbnQnICh3aXRoIGFuIGUpIG1lYW5zICdzb21ldGhpbmcgdGhhdCBjb21wbGV0ZXMgb3IgZ29lcyB3ZWxsIHdpdGgnOyAnY29tcGxpbWVudCcgaXMgcHJhaXNlLiJdLFsiSSBuZWVkIHNvbWUgcGFwZXIgYW5kIGFuIGVudmVsb3BlIGZyb20gdGhlIF9fXyBzaG9wLiIsInN0YXRpb25lcnkiLFsic3RhdGlvbmFyeSJdLCInU3RhdGlvbmVyeScgKHdpdGggYW4gZSkgaXMgcGFwZXIgYW5kIHBlbnM7ICdzdGF0aW9uYXJ5JyAod2l0aCBhbiBhKSBtZWFucyAnbm90IG1vdmluZycuIl0sWyJUaGUgY2FyIHN0YXllZCBfX18gYXQgdGhlIHRyYWZmaWMgbGlnaHRzLiIsInN0YXRpb25hcnkiLFsic3RhdGlvbmVyeSJdLCInU3RhdGlvbmFyeScgKHdpdGggYW4gYSkgbWVhbnMgJ25vdCBtb3ZpbmcnOyAnc3RhdGlvbmVyeScgKHdpdGggYW4gZSkgaXMgcGFwZXIgYW5kIHBlbnMuIl0sWyJJIG5lZWQgc29tZSBfX18gYWJvdXQgbXkgcHJvamVjdC4iLCJhZHZpY2UiLFsiYWR2aXNlIl0sIidBZHZpY2UnICh3aXRoIGEgYykgaXMgYSBub3VuOyAnYWR2aXNlJyAod2l0aCBhbiBzKSBpcyBhIHZlcmIuIl0sWyJDYW4geW91IF9fXyBtZSBvbiB3aGljaCBib29rIHRvIGJ1eT8iLCJhZHZpc2UiLFsiYWR2aWNlIl0sIidBZHZpc2UnICh3aXRoIGFuIHMpIGlzIGEgdmVyYjsgJ2FkdmljZScgKHdpdGggYSBjKSBpcyBhIG5vdW4uIl0sWyJJdCB3YXMgX19fIGNvbGQgb3V0c2lkZSB0b2RheS4iLCJxdWl0ZSIsWyJxdWlldCJdLCInUXVpdGUnIG1lYW5zICdmYWlybHknIG9yICd2ZXJ5JzsgJ3F1aWV0JyBtZWFucyAnbWFraW5nIGxpdHRsZSBub2lzZScuIl0sWyJQbGVhc2UgYmUgX19fIGluIHRoZSBsaWJyYXJ5LiIsInF1aWV0IixbInF1aXRlIl0sIidRdWlldCcgbWVhbnMgJ21ha2luZyBsaXR0bGUgbm9pc2UnOyAncXVpdGUnIG1lYW5zICdmYWlybHknLiJdXQ==");
const PUNCT: [string, string[], string][] = unpack("W1siSSBsb3ZlIHJlYWRpbmc7IG15IGJyb3RoZXIgcHJlZmVycyBzcG9ydC4iLFsiSSBsb3ZlIHJlYWRpbmcsIG15IGJyb3RoZXIgcHJlZmVycyBzcG9ydC4iLCJJIGxvdmUgcmVhZGluZzsgYW5kIG15IGJyb3RoZXIgcHJlZmVycyBzcG9ydC4iXSwiQSBzZW1pY29sb24gam9pbnMgdHdvIGNsb3NlbHkgcmVsYXRlZCBjb21wbGV0ZSBzZW50ZW5jZXMuIEEgY29tbWEgYWxvbmUgd291bGQgbWFrZSBhIGNvbW1hIHNwbGljZSwgYW5kIGEgc2VtaWNvbG9uIHNob3VsZCBub3QgYmUgZm9sbG93ZWQgYnkgJ2FuZCcuIl0sWyJZb3Ugd2lsbCBuZWVkIHRocmVlIHRoaW5nczogYSBwZW5jaWwsIGEgcnVsZXIgYW5kIGFuIGVyYXNlci4iLFsiWW91IHdpbGwgbmVlZDogdGhyZWUgdGhpbmdzIGEgcGVuY2lsLCBhIHJ1bGVyIGFuZCBhbiBlcmFzZXIuIiwiWW91IHdpbGwgbmVlZCB0aHJlZSB0aGluZ3M7IGEgcGVuY2lsLCBhIHJ1bGVyIGFuZCBhbiBlcmFzZXIuIl0sIkEgY29sb24gY29tZXMgYWZ0ZXIgYSBjb21wbGV0ZSBzdGF0ZW1lbnQgdG8gaW50cm9kdWNlIGEgbGlzdC4iXSxbIkFmdGVyIGx1bmNoLCB3ZSBwbGF5ZWQgY3JpY2tldC4iLFsiQWZ0ZXIgbHVuY2ggd2UsIHBsYXllZCBjcmlja2V0LiIsIkFmdGVyLCBsdW5jaCB3ZSBwbGF5ZWQgY3JpY2tldC4iXSwiUHV0IGEgY29tbWEgYWZ0ZXIgYW4gb3BlbmluZyBwaHJhc2UsIGJlZm9yZSB0aGUgbWFpbiBwYXJ0IG9mIHRoZSBzZW50ZW5jZS4iXSxbIlwiQ29tZSBoZXJlLFwiIHNhaWQgTXVtLiIsWyJcIkNvbWUgaGVyZVwiLCBzYWlkIE11bS4iLCJcIkNvbWUgaGVyZS5cIiBzYWlkIE11bS4iXSwiSW4gc3BlZWNoLCB0aGUgY29tbWEgZ29lcyBpbnNpZGUgdGhlIHF1b3RhdGlvbiBtYXJrcywgYW5kIHRoZSBzZW50ZW5jZSBjYXJyaWVzIG9uIHdpdGggYSBzbWFsbCBsZXR0ZXIuIl0sWyJIZSBoYWQgb25lIGdvYWw6IHRvIHdpbi4iLFsiSGUgaGFkIG9uZSBnb2FsLCB0byB3aW4uIiwiSGUgaGFkOiBvbmUgZ29hbCB0byB3aW4uIl0sIkEgY29sb24gaW50cm9kdWNlcyBhbiBleHBsYW5hdGlvbiBhZnRlciBhIGNvbXBsZXRlIHN0YXRlbWVudC4iXSxbIldlIHZpc2l0ZWQgUGFyaXMsIEZyYW5jZTsgUm9tZSwgSXRhbHk7IGFuZCBNYWRyaWQsIFNwYWluLiIsWyJXZSB2aXNpdGVkIFBhcmlzLCBGcmFuY2UsIFJvbWUsIEl0YWx5LCBhbmQgTWFkcmlkLCBTcGFpbi4iLCJXZSB2aXNpdGVkIFBhcmlzOyBGcmFuY2UsIFJvbWU7IEl0YWx5LCBhbmQgTWFkcmlkOyBTcGFpbi4iXSwiV2hlbiBsaXN0IGl0ZW1zIGFscmVhZHkgY29udGFpbiBjb21tYXMsIHVzZSBzZW1pY29sb25zIHRvIHNlcGFyYXRlIHRoZSBpdGVtcy4iXSxbIk15IGJyb3RoZXIsIHdobyBsaXZlcyBpbiBQZXJ0aCwgaXMgYSBkb2N0b3IuIixbIk15IGJyb3RoZXIgd2hvIGxpdmVzIGluIFBlcnRoLCBpcyBhIGRvY3Rvci4iLCJNeSBicm90aGVyLCB3aG8gbGl2ZXMgaW4gUGVydGggaXMgYSBkb2N0b3IuIl0sIkV4dHJhIGluZm9ybWF0aW9uIGlzIHB1dCBiZXR3ZWVuIGEgcGFpciBvZiBjb21tYXMsIG9uZSBiZWZvcmUgYW5kIG9uZSBhZnRlci4iXSxbIlwiQXJlIHlvdSBjb21pbmc/XCIgc2hlIGFza2VkLiIsWyJcIkFyZSB5b3UgY29taW5nXCI/IHNoZSBhc2tlZC4iLCJcIkFyZSB5b3UgY29taW5nP1wiIFNoZSBhc2tlZC4iXSwiVGhlIHF1ZXN0aW9uIG1hcmsgYmVsb25ncyB0byB0aGUgc3Bva2VuIHdvcmRzLCBzbyBpdCBnb2VzIGluc2lkZSB0aGUgcXVvdGF0aW9uIG1hcmtzLCBhbmQgJ3NoZSBhc2tlZCcgY29udGludWVzIHRoZSBzZW50ZW5jZS4iXSxbIkkgd2FzIHRpcmVkLCBidXQgSSBrZXB0IGdvaW5nLiIsWyJJIHdhcyB0aXJlZCBidXQsIEkga2VwdCBnb2luZy4iLCJJIHdhcyB0aXJlZCwgYnV0LCBJIGtlcHQgZ29pbmcuIl0sIlB1dCB0aGUgY29tbWEgYmVmb3JlIHRoZSBqb2luaW5nIHdvcmQgKGJ1dCkgd2hlbiBpdCBsaW5rcyB0d28gY29tcGxldGUgc2VudGVuY2VzLiJdLFsiVGhlIHJ1bGUgaXMgc2ltcGxlOiBhbHdheXMgY2hlY2sgeW91ciB3b3JrLiIsWyJUaGUgcnVsZSBpcyBzaW1wbGUsIGFsd2F5cyBjaGVjayB5b3VyIHdvcmsuIiwiVGhlIHJ1bGUgaXM6IHNpbXBsZSBhbHdheXMgY2hlY2sgeW91ciB3b3JrLiJdLCJBIGNvbG9uIGNvbWVzIGFmdGVyIGEgY29tcGxldGUgc3RhdGVtZW50IHRvIGludHJvZHVjZSBhbiBleHBsYW5hdGlvbi4iXSxbIkl0IHdhcyByYWluaW5nOyB0aGUgbWF0Y2ggd2FzIGNhbmNlbGxlZC4iLFsiSXQgd2FzIHJhaW5pbmcsIHRoZSBtYXRjaCB3YXMgY2FuY2VsbGVkLiIsIkl0IHdhcyByYWluaW5nIHRoZTsgbWF0Y2ggd2FzIGNhbmNlbGxlZC4iXSwiQSBzZW1pY29sb24gY2FuIGpvaW4gdHdvIHJlbGF0ZWQgY29tcGxldGUgc2VudGVuY2VzIHdpdGhvdXQgYSBqb2luaW5nIHdvcmQuIl0sWyJTaGUgcGFja2VkIHRoZSBlc3NlbnRpYWxzOiBhIHRvcmNoLCBhIG1hcCBhbmQgYSBjb21wYXNzLiIsWyJTaGUgcGFja2VkOiB0aGUgZXNzZW50aWFscyBhIHRvcmNoLCBhIG1hcCBhbmQgYSBjb21wYXNzLiIsIlNoZSBwYWNrZWQgdGhlIGVzc2VudGlhbHMsIGEgdG9yY2g7IGEgbWFwIGFuZCBhIGNvbXBhc3MuIl0sIkEgY29sb24gaW50cm9kdWNlcyB0aGUgbGlzdCBhZnRlciB0aGUgY29tcGxldGUgc3RhdGVtZW50ICdTaGUgcGFja2VkIHRoZSBlc3NlbnRpYWxzJy4iXV0=");
const POV: [string, string][] = unpack("W1siSSB3YWxrZWQgdG8gdGhlIHNob3AgYW5kIGJvdWdodCBzb21lIG1pbGsuIiwiZmlyc3QgcGVyc29uIl0sWyJZb3Ugc2hvdWxkIGFsd2F5cyBjaGVjayB5b3VyIHdvcmsuIiwic2Vjb25kIHBlcnNvbiJdLFsiU2hlIG9wZW5lZCB0aGUgZG9vciBzbG93bHkuIiwidGhpcmQgcGVyc29uIl0sWyJXZSBhcmUgZ29pbmcgb24gYSBob2xpZGF5IG5leHQgd2Vlay4iLCJmaXJzdCBwZXJzb24iXSxbIllvdSB3aWxsIGxvdmUgdGhpcyByZWNpcGUuIiwic2Vjb25kIHBlcnNvbiJdLFsiVGhleSBjcm9zc2VkIHRoZSBicmlkZ2UgYXQgZGF3bi4iLCJ0aGlyZCBwZXJzb24iXSxbIk15IGhlYXJ0IHJhY2VkIGFzIEkgc3RlcHBlZCBvbiB0byB0aGUgc3RhZ2UuIiwiZmlyc3QgcGVyc29uIl0sWyJIZSB3b25kZXJlZCB3aGV0aGVyIHRoZSBsZXR0ZXIgd291bGQgZXZlciBhcnJpdmUuIiwidGhpcmQgcGVyc29uIl0sWyJJbWFnaW5lIHlvdSBhcmUgc3RhbmRpbmcgYXQgdGhlIGVkZ2Ugb2YgYSBjbGlmZi4iLCJzZWNvbmQgcGVyc29uIl0sWyJPdXIgdGVhbSBwcmFjdGlzZWQgZXZlcnkgZGF5IGJlZm9yZSB0aGUgZmluYWwuIiwiZmlyc3QgcGVyc29uIl0sWyJIYXZlIHlvdSBldmVyIHdvbmRlcmVkIHdoeSB0aGUgc2t5IGlzIGJsdWU/Iiwic2Vjb25kIHBlcnNvbiJdLFsiVGhlIG9sZCBmaXNoZXJtYW4gd2F0Y2hlZCB0aGUgYm9hdHMgY29tZSBpbi4iLCJ0aGlyZCBwZXJzb24iXSxbIkkgY291bGQgbm90IGRlY2lkZSB3aGljaCBwYXRoIHRvIHRha2UuIiwiZmlyc3QgcGVyc29uIl0sWyJNYXJpYSBwYWNrZWQgaGVyIGJhZyBhbmQgbGVmdCBlYXJseS4iLCJ0aGlyZCBwZXJzb24iXV0=");
const CONNOTATION: [string, string][] = unpack("W1sidGhyaWZ0eSIsInN0aW5neSJdLFsiY3VyaW91cyIsIm5vc3kiXSxbImNvbmZpZGVudCIsImFycm9nYW50Il0sWyJkZXRlcm1pbmVkIiwic3R1YmJvcm4iXSxbInNsZW5kZXIiLCJza2lubnkiXSxbInJlbGF4ZWQiLCJsYXp5Il0sWyJjYXV0aW91cyIsImNvd2FyZGx5Il0sWyJmcnVnYWwiLCJjaGVhcCJdLFsiYXNzZXJ0aXZlIiwiYm9zc3kiXSxbInlvdXRoZnVsIiwiaW1tYXR1cmUiXSxbImZyYWdyYW5jZSIsInN0ZW5jaCJdLFsidW5pcXVlIiwib2RkIl0sWyJkYXJpbmciLCJyZWNrbGVzcyJdLFsiY2hhdHR5IiwiZ29zc2lweSJdXQ==");
const APPEALS: [string, string][] = unpack("W1siQXMgYSBkb2N0b3Igd2l0aCB0d2VudHkgeWVhcnMnIGV4cGVyaWVuY2UsIEkgY2FuIHRlbGwgeW91IHRoaXMgdHJlYXRtZW50IGlzIHNhZmUuIiwiZXRob3MiXSxbIkltYWdpbmUgYSBsb25lbHkgcHVwcHkgc2hpdmVyaW5nIGluIHRoZSBjb2xkLCB3YWl0aW5nIGZvciBzb21lb25lIHRvIHRha2UgaXQgaG9tZS4iLCJwYXRob3MiXSxbIlN0dWRpZXMgc2hvdyB0aGF0IHN0dWRlbnRzIHdobyBzbGVlcCBlaWdodCBob3VycyBzY29yZSBmaWZ0ZWVuIHBlciBjZW50IGhpZ2hlciBvbiB0ZXN0cy4iLCJsb2dvcyJdLFsiVHJ1c3QgbWU6IEkgaGF2ZSBydW4gdGhpcyBjb21wYW55IGZvciB0aGlydHkgeWVhcnMuIiwiZXRob3MiXSxbIklmIHdlIGRvIG5vdCBhY3QsIG91ciBjaGlsZHJlbiB3aWxsIGluaGVyaXQgYSBiYXJyZW4sIGxpZmVsZXNzIHBsYW5ldC4iLCJwYXRob3MiXSxbIlNpbmNlIGVsZWN0cmljIGNhcnMgcHJvZHVjZSBubyBleGhhdXN0IGFuZCB0aGUgZ3JpZCBpcyBnZXR0aW5nIGNsZWFuZXIsIHRvdGFsIGVtaXNzaW9ucyBtdXN0IGZhbGwuIiwibG9nb3MiXSxbIlRoaXMgcHJvZHVjdCBpcyBlbmRvcnNlZCBieSBsZWFkaW5nIHNjaWVudGlzdHMgZnJvbSB0aHJlZSB1bml2ZXJzaXRpZXMuIiwiZXRob3MiXSxbIlRoaW5rIG9mIHRoZSBmYW1pbGllcyB0b3JuIGFwYXJ0IGJ5IHRoaXMgcG9saWN5LiIsInBhdGhvcyJdLFsiVGhlIHBvcHVsYXRpb24gaGFzIGRvdWJsZWQgd2hpbGUgdGhlIG51bWJlciBvZiBidXNlcyBoYXMgc3RheWVkIHRoZSBzYW1lLCBzbyBvdmVyY3Jvd2RpbmcgaXMgaW5ldml0YWJsZS4iLCJsb2dvcyJdLFsiQXMgYSBmb3JtZXIgdGVhY2hlciwgSSBrbm93IGV4YWN0bHkgd2hhdCBzdHVkZW50cyBuZWVkLiIsImV0aG9zIl0sWyJUaGUgZGF0YSBzaG93IGEgZm9ydHkgcGVyIGNlbnQgZHJvcCBpbiBhY2NpZGVudHMgYWZ0ZXIgdGhlIGxhdyB3YXMgaW50cm9kdWNlZC4iLCJsb2dvcyJdLFsiSG93IGNhbiB3ZSBsb29rIGludG8gdGhlIGV5ZXMgb2YgaHVuZ3J5IGNoaWxkcmVuIGFuZCBkbyBub3RoaW5nPyIsInBhdGhvcyJdLFsiT3VyIGF3YXJkLXdpbm5pbmcgdGVhbSBpcyB0cnVzdGVkIGJ5IGhvc3BpdGFscyBhY3Jvc3MgdGhlIGNvdW50cnkuIiwiZXRob3MiXSxbIkV2ZXJ5IHllYXIgMzAwMCBwZW9wbGUgYXJlIGluanVyZWQsIGFuZCBhIGJhbiB3b3VsZCBjb3N0IGxlc3MgdGhhbiB0aGVpciBtZWRpY2FsIGJpbGxzLiIsImxvZ29zIl0sWyJJdCBicmVha3MgbXkgaGVhcnQgdG8gc2VlIHRoZSBiZWF1dGlmdWwgb2xkIHRyZWVzIGN1dCBkb3duLiIsInBhdGhvcyJdXQ==");
const PARALLEL: [string, string, string][] = unpack("W1siU2hlIGVuam95cyByZWFkaW5nLCB3cml0aW5nIGFuZCBwYWludGluZy4iLCJTaGUgZW5qb3lzIHJlYWRpbmcsIHdyaXRpbmcgYW5kIHRvIHBhaW50LiIsIlRoZSBpdGVtcyBpbiBhIGxpc3Qgc2hvdWxkIHNoYXJlIHRoZSBzYW1lIGZvcm0uIEhlcmUgYWxsIHRocmVlIGFyZSAtaW5nIHdvcmRzLiJdLFsiVGhlIGpvYiByZXF1aXJlcyBwYXRpZW5jZSwgaG9uZXN0eSBhbmQgY3JlYXRpdml0eS4iLCJUaGUgam9iIHJlcXVpcmVzIGJlaW5nIHBhdGllbnQsIGhvbmVzdHkgYW5kIGNyZWF0aXZpdHkuIiwiVGhlIHRocmVlIGl0ZW1zIHNob3VsZCBhbGwgYmUgbm91bnM6IHBhdGllbmNlLCBob25lc3R5LCBjcmVhdGl2aXR5LiJdLFsiSGUgcGxhbnMgdG8gc3R1ZHkgbGF3LCB0byB0cmF2ZWwgd2lkZWx5IGFuZCB0byB3cml0ZSBhIGJvb2suIiwiSGUgcGxhbnMgdG8gc3R1ZHkgbGF3LCB0cmF2ZWxsaW5nIHdpZGVseSBhbmQgdG8gd3JpdGUgYSBib29rLiIsIkFsbCB0aHJlZSBpdGVtcyBzaG91bGQgdXNlIHRoZSBzYW1lIGZvcm0gKHRvICsgdmVyYikuIl0sWyJUaGUgc3BlZWNoIHdhcyBsb25nLCBib3JpbmcgYW5kIHJlcGV0aXRpdmUuIiwiVGhlIHNwZWVjaCB3YXMgbG9uZywgYm9yaW5nIGFuZCBpdCByZXBlYXRlZCBpdHNlbGYuIiwiQWxsIHRocmVlIHNob3VsZCBiZSBhZGplY3RpdmVzOiBsb25nLCBib3JpbmcsIHJlcGV0aXRpdmUuIl0sWyJUaGV5IGNhbiBlaXRoZXIgd2FsayB0byBzY2hvb2wgb3IgdGFrZSB0aGUgYnVzLiIsIlRoZXkgY2FuIGVpdGhlciB3YWxrIHRvIHNjaG9vbCBvciB0aGUgYnVzLiIsIkFmdGVyICdlaXRoZXIgLi4uIG9yJywgYm90aCBwYXJ0cyBzaG91bGQgaGF2ZSB0aGUgc2FtZSBmb3JtOiBhIHZlcmIgcGhyYXNlIGVhY2guIl0sWyJZb3UgY2FuIHBheSBieSBjYXNoLCBieSBjYXJkIG9yIGJ5IGNoZXF1ZS4iLCJZb3UgY2FuIHBheSBieSBjYXNoLCB3aXRoIGEgY2FyZCBvciB1c2luZyBjaGVxdWUuIiwiUmVwZWF0IHRoZSBzYW1lIHBhdHRlcm4gKGJ5ICsgbm91bikgZm9yIGV2ZXJ5IGl0ZW0uIl0sWyJPdXIgZ29hbHMgYXJlIHRvIHJlZHVjZSB3YXN0ZSwgdG8gc2F2ZSBlbmVyZ3kgYW5kIHRvIHByb3RlY3Qgd2lsZGxpZmUuIiwiT3VyIGdvYWxzIGFyZSByZWR1Y2luZyB3YXN0ZSwgdG8gc2F2ZSBlbmVyZ3kgYW5kIHByb3RlY3Rpbmcgd2lsZGxpZmUuIiwiQWxsIGl0ZW1zIHNob3VsZCB1c2UgdGhlIHNhbWUgZm9ybSAodG8gKyB2ZXJiKSBpbnN0ZWFkIG9mIG1peGluZyAtaW5nIGFuZCB0by4iXSxbIlRoZSBjb2FjaCB0b2xkIHRoZSB0ZWFtIHRvIGFycml2ZSBlYXJseSwgdG8gd2FybSB1cCBhbmQgdG8gc3RheSBmb2N1c2VkLiIsIlRoZSBjb2FjaCB0b2xkIHRoZSB0ZWFtIHRvIGFycml2ZSBlYXJseSwgd2FybWluZyB1cCBhbmQgc3RheSBmb2N1c2VkLiIsIktlZXAgdGhlIHNhbWUgZm9ybSBmb3IgZXZlcnkgaXRlbSAodG8gKyB2ZXJiKS4iXSxbIlNoZSBpcyBub3Qgb25seSB0YWxlbnRlZCBidXQgYWxzbyBoYXJkd29ya2luZy4iLCJTaGUgaXMgbm90IG9ubHkgdGFsZW50ZWQgYnV0IGFsc28gd29ya3MgaGFyZC4iLCJBZnRlciAnbm90IG9ubHkgLi4uIGJ1dCBhbHNvJywgYm90aCBwYXJ0cyBzaG91bGQgYmUgdGhlIHNhbWUga2luZCBvZiB3b3JkIChhZGplY3RpdmVzKS4iXSxbIkhlIGxpa2VzIHRvIHN3aW0sIHRvIGN5Y2xlIGFuZCB0byBydW4uIiwiSGUgbGlrZXMgdG8gc3dpbSwgY3ljbGluZyBhbmQgdG8gcnVuLiIsIktlZXAgdGhlIHNhbWUgZm9ybSBmb3IgZXZlcnkgaXRlbSAodG8gKyB2ZXJiKS4iXV0=");
const CONCISE: [string, string, string][] = unpack("W1siQmVjYXVzZSBpdCByYWluZWQsIHdlIHN0YXllZCBpbnNpZGUuIiwiRHVlIHRvIHRoZSBmYWN0IHRoYXQgaXQgcmFpbmVkLCB3ZSBzdGF5ZWQgaW5zaWRlLiIsIidEdWUgdG8gdGhlIGZhY3QgdGhhdCcgaXMgYSB3b3JkeSB3YXkgdG8gc2F5ICdiZWNhdXNlJy4iXSxbIkFsdGhvdWdoIGl0IHdhcyBsYXRlLCB3ZSBrZXB0IHdvcmtpbmcuIiwiSW4gc3BpdGUgb2YgdGhlIGZhY3QgdGhhdCBpdCB3YXMgbGF0ZSwgd2Uga2VwdCB3b3JraW5nLiIsIidJbiBzcGl0ZSBvZiB0aGUgZmFjdCB0aGF0JyBjYW4gYmUgcmVwbGFjZWQgYnkgJ2FsdGhvdWdoJy4iXSxbIldlIG5lZWQgdG8gZGVjaWRlIG5vdy4iLCJXZSBuZWVkIHRvIGRlY2lkZSBhdCB0aGlzIHBvaW50IGluIHRpbWUuIiwiJ0F0IHRoaXMgcG9pbnQgaW4gdGltZScganVzdCBtZWFucyAnbm93Jy4iXSxbIkhlIGxlZnQgYmVjYXVzZSBoZSB3YXMgdGlyZWQuIiwiVGhlIHJlYXNvbiB3aHkgaGUgbGVmdCBpcyBiZWNhdXNlIGhlIHdhcyB0aXJlZC4iLCInVGhlIHJlYXNvbiB3aHkgLi4uIGlzIGJlY2F1c2UnIHJlcGVhdHMgdGhlIHNhbWUgaWRlYTsgJ2JlY2F1c2UnIGlzIGVub3VnaC4iXSxbIlNoZSBsb3ZlcyBtdXNpYy4iLCJTaGUgaXMgYSBwZXJzb24gd2hvIGxvdmVzIG11c2ljLiIsIidJcyBhIHBlcnNvbiB3aG8nIGFkZHMgd29yZHMgYnV0IG5vIG1lYW5pbmcuIl0sWyJUaGUgcmVwb3J0IHdhcyBmaW5pc2hlZC4iLCJUaGUgcmVwb3J0IHdhcyBjb21wbGV0ZWx5IGZpbmlzaGVkIGFuZCBkb25lLiIsIidGaW5pc2hlZCcgYW5kICdkb25lJyBtZWFuIHRoZSBzYW1lLCBzbyBvbmUgd29yZCBpcyBlbm91Z2guIl0sWyJJZiBpdCByYWlucywgd2Ugd2lsbCBzdGF5IGhvbWUuIiwiSW4gdGhlIGV2ZW50IHRoYXQgaXQgcmFpbnMsIHdlIHdpbGwgc3RheSBob21lLiIsIidJbiB0aGUgZXZlbnQgdGhhdCcgY2FuIGJlIHJlcGxhY2VkIGJ5ICdpZicuIl0sWyJIZSByZXR1cm5lZCBob21lLiIsIkhlIHJldHVybmVkIGJhY2sgdG8gaGlzIGhvbWUuIiwiJ1JldHVybmVkJyBhbHJlYWR5IG1lYW5zICd3ZW50IGJhY2snLCBzbyAnYmFjaycgaXMgcmVwZWF0ZWQuIl0sWyJFdmVyeSBzdHVkZW50IG11c3QgYXR0ZW5kLiIsIkVhY2ggYW5kIGV2ZXJ5IHN0dWRlbnQgbXVzdCBhdHRlbmQuIiwiJ0VhY2ggYW5kIGV2ZXJ5JyBzYXlzIHRoZSBzYW1lIHRoaW5nIHR3aWNlLiJdLFsiV2Ugd2lsbCBtZWV0IGF0IDMgcG0uIiwiV2Ugd2lsbCBtZWV0IGF0IDMgcG0gaW4gdGhlIGFmdGVybm9vbi4iLCIncG0nIGFscmVhZHkgbWVhbnMgYWZ0ZXJub29uLCBzbyAnaW4gdGhlIGFmdGVybm9vbicgaXMgcmVkdW5kYW50LiJdLFsiVGhlIG91dGNvbWUgd2FzIGEgc3VycHJpc2UuIiwiVGhlIGZpbmFsIG91dGNvbWUgd2FzIGEgc3VycHJpc2UuIiwiQW4gb3V0Y29tZSBpcyBhbHJlYWR5IHRoZSBlbmQgcmVzdWx0LCBzbyAnZmluYWwnIGFkZHMgbm90aGluZy4iXSxbIlRoZSB0d28gb2YgdGhlbSBtZXQgZWFybHkuIiwiVGhlIHR3byBvZiB0aGVtIG1ldCB0b2dldGhlciBlYXJseS4iLCInTWV0JyBhbHJlYWR5IG1lYW5zIHRoZXkgd2VyZSB0b2dldGhlci4iXV0=");

interface ChoiceItem {
  prompt: string;
  answer: string;
  distractors: string[];
  explanation: string;
}

function choiceTopic(id: string, label: string, items: ChoiceItem[]): Topic {
  return {
    id,
    label,
    generate: () => {
      const item = pick(items);
      return {
        prompt: item.prompt,
        answer: item.answer,
        options: shuffle([item.answer, ...item.distractors]),
        explanation: item.explanation,
      };
    },
  };
}

export function compoundWords(): Topic {
  return bankMCQ(
    "compound-words",
    "Compound words",
    COMPOUND.map(([a, b, whole]) => ({
      prompt: `Which word do you make by joining "${a}" and "${b}"?`,
      answer: whole,
      explanation: `A compound word joins two smaller words into one new word: ${a} + ${b} = ${whole}.`,
    })),
  );
}

const SENTENCE_TYPE_NOTE: Record<string, string> = {
  statement: "tells us something and ends with a full stop (.)",
  question: "asks something and ends with a question mark (?)",
  exclamation: "shows strong feeling and ends with an exclamation mark (!)",
  command: "tells someone to do something, usually starting with a verb",
};

export function sentenceTypes(): Topic {
  return bankMCQ(
    "sentence-types",
    "Types of sentences",
    SENTENCE_TYPES.map(([sentence, type]) => ({
      prompt: `What type of sentence is this? "${sentence}"`,
      answer: type,
      explanation: `It is ${article(type)} ${type}: ${article(type)} ${type} ${SENTENCE_TYPE_NOTE[type]}.`,
    })),
    ["statement", "question", "exclamation", "command"],
  );
}

function spellingTopic(id: string, label: string, bank: [string, string[], string][]): Topic {
  return choiceTopic(
    id,
    label,
    bank.map(([word, wrong, tip], i) => ({
      prompt: `Spelling ${i + 1}: which spelling is correct?`,
      answer: word,
      distractors: wrong,
      explanation: `The correct spelling is "${word}". The others (${wrong.map((w) => `"${w}"`).join(", ")}) are common mistakes.${tip ? ` Tip: ${tip}` : ""}`,
    })),
  );
}

const anchor = (sentence: string) => sentence.split(" ").slice(0, 4).join(" ");

export function spellingEasy(): Topic {
  return spellingTopic("spelling-easy", "Choose the correct spelling", SPELL_EASY);
}

export function spellingHard(): Topic {
  return spellingTopic("spelling-hard", "Tricky spellings", SPELL_HARD);
}

export function suffixes(): Topic {
  return bankFill(
    "suffixes",
    "Adding suffixes",
    SUFFIXES.map(([base, suffix, result, note]) => ({
      prompt: `Add the suffix -${suffix} to "${base}". What is the new word?`,
      answer: result,
      explanation: `${cap(note)} So "${base}" + -${suffix} = "${result}".`,
    })),
  );
}

export function subjectVerbAgreement(): Topic {
  return choiceTopic(
    "subject-verb-agreement",
    "Subject-verb agreement",
    AGREEMENT.map(([sentence, ok, bad, why]) => ({
      prompt: `Choose the correct word: "${sentence}"`,
      answer: ok,
      distractors: [bad],
      explanation: `${why} Correct sentence: "${sentence.replace("___", ok)}"`,
    })),
  );
}

export function possessiveApostrophes(): Topic {
  return choiceTopic(
    "possessive-apostrophes",
    "Apostrophes for belonging",
    POSSESSIVE.map(([desc, ok, bad, why]) => ({
      prompt: `Which phrase is written correctly when ${desc}?`,
      answer: ok,
      distractors: bad,
      explanation: `${why} Correct: "${ok}".`,
    })),
  );
}

const STRUCTURE_NOTE: Record<string, string> = {
  simple: "one independent clause (one complete idea)",
  compound: "two independent clauses joined by a linking word such as and, but, so, or, yet",
  complex: "an independent clause plus a dependent clause that starts with a word such as because, although, when, if",
};

export function sentenceStructure(): Topic {
  return bankMCQ(
    "sentence-structure",
    "Simple, compound and complex sentences",
    STRUCTURE.map(([sentence, kind]) => ({
      prompt: `Is this sentence simple, compound or complex? "${sentence}"`,
      answer: kind,
      explanation: `It is ${kind}. ${cap(article(kind))} ${kind} sentence has ${STRUCTURE_NOTE[kind]}.`,
    })),
    ["simple", "compound", "complex"],
  );
}

export function commonlyConfused(): Topic {
  return choiceTopic(
    "commonly-confused",
    "Commonly confused words",
    CONFUSED.map(([sentence, ok, bad, why]) => ({
      prompt: `Choose the correct word: "${sentence}"`,
      answer: ok,
      distractors: bad,
      explanation: `${why} Correct sentence: "${sentence.replace("___", ok)}"`,
    })),
  );
}

export function punctuationChoice(): Topic {
  return choiceTopic(
    "punctuation-choice",
    "Colons, semicolons and commas",
    PUNCT.map(([ok, bad, why]) => ({
      prompt: `Which version of the sentence beginning "${anchor(ok)}" is punctuated correctly?`,
      answer: ok,
      distractors: bad,
      explanation: `${why} Correct: ${ok}`,
    })),
  );
}

const POV_NOTE: Record<string, string> = {
  "first person": "uses I, me, my, we or our, because the speaker is part of the story",
  "second person": "speaks directly to the reader using you or your",
  "third person": "talks about other people using he, she, they or names",
};

export function pointOfView(): Topic {
  return bankMCQ(
    "point-of-view",
    "Point of view",
    POV.map(([sentence, pov]) => ({
      prompt: `Which point of view is this written in? "${sentence}"`,
      answer: pov,
      explanation: `It is ${pov}: writing in ${pov} ${POV_NOTE[pov]}.`,
    })),
    ["first person", "second person", "third person"],
  );
}

export function connotation(): Topic {
  const items: ChoiceItem[] = CONNOTATION.flatMap(([good, bad]) => [
    {
      prompt: `Which word has a more positive connotation: "${good}" or "${bad}"?`,
      answer: good,
      distractors: [bad],
      explanation: `Both words describe something similar, but "${good}" suggests approval and "${bad}" suggests criticism. That difference in feeling is the connotation.`,
    },
    {
      prompt: `Which word has a more negative connotation: "${good}" or "${bad}"?`,
      answer: bad,
      distractors: [good],
      explanation: `Both words describe something similar, but "${bad}" suggests criticism and "${good}" suggests approval. That difference in feeling is the connotation.`,
    },
  ]);
  return choiceTopic("connotation", "Connotation", items);
}

const APPEAL_NOTE: Record<string, string> = {
  ethos: "builds trust by pointing to the speaker's credibility, experience or expert backing",
  pathos: "works on the audience's emotions, such as pity, fear or joy",
  logos: "relies on logic, using facts, data and reasoning",
};

export function rhetoricalAppeals(): Topic {
  return bankMCQ(
    "rhetorical-appeals",
    "Ethos, pathos and logos",
    APPEALS.map(([example, appeal]) => ({
      prompt: `Which rhetorical appeal is used here? "${example}"`,
      answer: appeal,
      explanation: `It is ${appeal}: this appeal ${APPEAL_NOTE[appeal]}.`,
    })),
    ["ethos", "pathos", "logos"],
  );
}

export function parallelStructure(): Topic {
  return choiceTopic(
    "parallel-structure",
    "Parallel structure",
    PARALLEL.map(([ok, bad, why]) => ({
      prompt: `Which version of the sentence beginning "${anchor(ok)}" uses parallel structure correctly?`,
      answer: ok,
      distractors: [bad],
      explanation: `${why} Correct: ${ok}`,
    })),
  );
}

export function conciseWriting(): Topic {
  return choiceTopic(
    "concise-writing",
    "Concise writing",
    CONCISE.map(([ok, wordy, why], i) => ({
      prompt: `Concise writing ${i + 1}: which sentence says the same thing more concisely?`,
      answer: ok,
      distractors: [wordy],
      explanation: `${why} Concise version: ${ok}`,
    })),
  );
}
